In [9]:
import pandas as pd

def data_processing(path = '../../sample_table/ewma_6h_scaling.csv'):
    data = pd.read_csv(path)    
    data = data[['REG_DTIME', 'h_dong', 'count']]
    data['REG_DTIME'] = pd.to_datetime(data['REG_DTIME'])
    data['DOW'] = data['REG_DTIME'].dt.dayofweek
    data['HOD'] = data['REG_DTIME'].dt.hour
    data['MOY'] = data['REG_DTIME'].dt.month
    for x , y in enumerate(data['REG_DTIME'].unique()):
        t_data_index = data[data['REG_DTIME'] == y].index
        data.loc[t_data_index , 'time_idx'] = int(x)    data['h_dong'] = data['h_dong'].astype(str)
    data['DOW'] = data['DOW'].astype(str)
    data['HOD'] = data['HOD'].astype(str)
    data['MOY'] = data['MOY'].astype(str)
    data['time_idx'] = data['time_idx'].astype(int)
    #data['count'] = data['count'].round(5)

    return data

In [10]:
x = data_processing('2010_2022_count.csv')

In [58]:
data = pd.read_csv('2010_2022_count.csv')
data = data[['REG_DTIME', 'h_dong', 'count']]
data['REG_DTIME'] = pd.to_datetime(data['REG_DTIME'])

In [62]:
for x , y in enumerate(data['REG_DTIME'].unique()):
    t_data_index = data[data['REG_DTIME'] == y].index
    data.loc[t_data_index , 'time_idx'] = x

In [63]:
data

         REG_DTIME h_dong  count  time_idx
0       2010-01-01    석사동      1       0.0
1       2010-01-01    신동면      0       0.0
2       2010-01-01    강남동      0       0.0
3       2010-01-01   서  면      0       0.0
4       2010-01-01   남  면      0       0.0
...            ...    ...    ...       ...
2238784 2022-03-01    퇴계동      0  106608.0
2238785 2022-03-01    북산면      0  106608.0
2238786 2022-03-01    조운동      0  106608.0
2238787 2022-03-01    동산면      0  106608.0
2238788 2022-03-01   교  동      0  106608.0

[2238789 rows x 4 columns]

In [88]:
data[data['REG_DTIME'] == '2021-01-01 00:00:00']

         REG_DTIME h_dong  count  time_idx
2025072 2021-01-01    석사동      0   96432.0
2025073 2021-01-01    신동면      0   96432.0
2025074 2021-01-01    강남동      0   96432.0
2025075 2021-01-01   서  면      0   96432.0
2025076 2021-01-01   남  면      0   96432.0
2025077 2021-01-01    사북면      0   96432.0
2025078 2021-01-01    동내면      0   96432.0
2025079 2021-01-01   효자1동      0   96432.0
2025080 2021-01-01    남산면      0   96432.0
2025081 2021-01-01    근화동      0   96432.0
2025082 2021-01-01   신사우동      0   96432.0
2025083 2021-01-01    신북읍      0   96432.0
2025084 2021-01-01    소양동      0   96432.0
2025085 2021-01-01   약사명동      0   96432.0
2025086 2021-01-01   동  면      0   96432.0
2025087 2021-01-01   후평1동      0   96432.0
2025088 2021-01-01    퇴계동      0   96432.0
2025089 2021-01-01    북산면      0   96432.0
2025090 2021-01-01    조운동      0   96432.0
2025091 2021-01-01    동산면      0   96432.0
2025092 2021-01-01   교  동      0   96432.0

In [86]:
365*24* 11

96360

In [89]:
96432 - 96360

72