In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('한국행정구역분류_2022.10.1.기준_20221006123917.xlsx' , sheet_name = '행정동 및 법정동코드와의 연계표', skiprows=1)

/home/nplab/.local/lib/python3.8/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [3]:
df

,시도,시군구,행정구역명,행정동\n(행정기관명),법정동,행정구역분류\n(개정_8자리),행정구역분류\n(7자리),행정기관코드,행정기관 생성일,법정동코드,법정동 관할구역\n분할여부,행정동 영문명칭,비고
0,서울특별시,서울특별시,서울특별시,서울특별시,서울특별시,11.0,11.0,1100000000,19880423,1100000000,NaN,Seoul,NaN
1,서울특별시,종로구,종로구,종로구,종로구,11010.0,11010.0,1111000000,19880423,1111000000,NaN,Jongno-gu,NaN
2,서울특별시,종로구,청운효자동,청운효자동,청운동,11010720.0,1101072.0,1111051500,20081101,1111010100,NaN,Cheongunhyoja-dong,NaN
3,서울특별시,종로구,청운효자동,청운효자동,신교동,11010720.0,1101072.0,1111051500,20081101,1111010200,NaN,Cheongunhyoja-dong,NaN
4,서울특별시,종로구,청운효자동,청운효자동,궁정동,11010720.0,1101072.0,1111051500,20081101,1111010300,NaN,Cheongunhyoja-dong,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21717,제주특별자치도,서귀포시,중문동,중문동,대포동,39020610.0,3902061.0,5013061000,20060701,5013011400,NaN,Jungmun-dong,NaN
21718,제주특별자치도,서귀포시,중문동,중문동,하원동,39020610.0,3902061.0,5013061000,20060701,5013011800,NaN,Jungmun-dong,NaN
21719,제주특별자치도,서귀포시,예래동,예래동,색달동,39020620.0,3902062.0,5013062000,20060701,5013011900,NaN,Yerae-dong,NaN
21720,제주특별자치도,서귀포시,예래동,예래동,상예동,39020620.0,3902062.0,5013062000,20060701,5013012000,NaN,Yerae-dong,NaN
21721,제주특별자치도,서귀포시,예래동,예래동,하예동,39020620.0,3902062.0,5013062000,20060701,5013012100,NaN,Yerae-dong,NaN

In [4]:
df = df[['시도' , '시군구','행정구역명' ,'행정동\n(행정기관명)', '법정동','법정동코드' , '행정구역분류\n(7자리)' ]]
df

            시도    시군구  행정구역명 행정동\n(행정기관명)    법정동       법정동코드  행정구역분류\n(7자리)
0        서울특별시  서울특별시  서울특별시        서울특별시  서울특별시  1100000000           11.0
1        서울특별시    종로구    종로구          종로구    종로구  1111000000        11010.0
2        서울특별시    종로구  청운효자동        청운효자동    청운동  1111010100      1101072.0
3        서울특별시    종로구  청운효자동        청운효자동    신교동  1111010200      1101072.0
4        서울특별시    종로구  청운효자동        청운효자동    궁정동  1111010300      1101072.0
...        ...    ...    ...          ...    ...         ...            ...
21717  제주특별자치도   서귀포시    중문동          중문동    대포동  5013011400      3902061.0
21718  제주특별자치도   서귀포시    중문동          중문동    하원동  5013011800      3902061.0
21719  제주특별자치도   서귀포시    예래동          예래동    색달동  5013011900      3902062.0
21720  제주특별자치도   서귀포시    예래동          예래동    상예동  5013012000      3902062.0
21721  제주특별자치도   서귀포시    예래동          예래동    하예동  5013012100      3902062.0

[21722 rows x 7 columns]

In [5]:
df = df[df['시군구'] =='춘천시']
df

       시도  시군구 행정구역명 행정동\n(행정기관명)  법정동       법정동코드  행정구역분류\n(7자리)
5232  강원도  춘천시   춘천시          춘천시  춘천시  4211000000        32010.0
5233  강원도  춘천시   신북읍          신북읍  신북읍  4211025000      3201011.0
5234  강원도  춘천시   신북읍          신북읍  율문리  4211025021      3201011.0
5235  강원도  춘천시   신북읍          신북읍  천전리  4211025022      3201011.0
5236  강원도  춘천시   신북읍          신북읍  유포리  4211025023      3201011.0
...   ...  ...   ...          ...  ...         ...            ...
5350  강원도  춘천시   강남동          강남동  칠전동  4211012600      3201068.0
5351  강원도  춘천시   강남동          강남동  송암동  4211012700      3201068.0
5352  강원도  춘천시  신사우동         신사우동  우두동  4211011800      3201071.0
5353  강원도  춘천시  신사우동         신사우동  사농동  4211011900      3201071.0
5354  강원도  춘천시  신사우동         신사우동   신동  4211012800      3201071.0

[123 rows x 7 columns]

In [6]:
df['행정구역명'].unique()

array(['춘천시', '신북읍', '동면', '동산면', '신동면', '남면', '서면', '사북면', '북산면', '동내면',
       '남산면', '교동', '조운동', '약사명동', '근화동', '소양동', '후평1동', '후평2동', '후평3동',
       '효자1동', '효자2동', '효자3동', '석사동', '퇴계동', '강남동', '신사우동'], dtype=object)

In [7]:
len(df['행정구역명'].unique())

26

In [8]:
df['법정동'].unique()

array(['춘천시', '신북읍', '율문리', '천전리', '유포리', '산천리', '발산리', '지내리', '용산리',
       '동면', '만천리', '장학리', '감정리', '월곡리', '품안리', '품걸리', '신이리', '평촌리',
       '상걸리', '동산면', '조양리', '봉명리', '원창리', '군자리', '신동면', '의암리', '팔미리',
       '혈동리', '증리', '정족리', '남면', '관천리', '박암리', '가정리', '후동리', '추곡리', '한덕리',
       '서면', '현암리', '금산리', '신매리', '서상리', '오월리', '월송리', '방동리', '덕두원리',
       '당림리', '안보리', '사북면', '신포리', '지촌리', '오탄리', '가일리', '원평리', '지암리',
       '고탄리', '고성리', '송암리', '인람리', '북산면', '내평리', '청평리', '부귀리', '오항리',
       '물로리', '조교리', '대동리', '대곡리', '추전리', '동내면', '거두리', '신촌리', '고은리',
       '사암리', '학곡리', '남산면', '광판리', '행촌리', '수동리', '창촌리', '방곡리', '강촌리',
       '서천리', '백양리', '방하리', '산수리', '교동', '조양동', '운교동', '중앙로2가', '중앙로3가',
       '죽림동', '약사동', '소양로1가', '근화동', '중도동', '봉의동', '요선동', '낙원동', '중앙로1가',
       '옥천동', '소양로2가', '소양로3가', '소양로4가', '후평동', '효자동', '석사동', '퇴계동',
       '온의동', '삼천동', '칠전동', '송암동', '우두동', '사농동', '신동'], dtype=object)

In [9]:
len(df['법정동'].unique()[1:])

114

## 행정구역 별 포함하는 법정동

In [22]:
for h_dong in df['행정동\n(행정기관명)'].unique():
    print(f'행정동  : {h_dong}')
    dong_df = df[df['행정동\n(행정기관명)'] == h_dong]
    STDC_CD = dong_df['법정동'].unique()
    print(f'법정동 : {STDC_CD}')

행정동  : 춘천시
법정동 : ['춘천시']
행정동  : 신북읍
법정동 : ['신북읍' '율문리' '천전리' '유포리' '산천리' '발산리' '지내리' '용산리']
행정동  : 동면
법정동 : ['동면' '지내리' '만천리' '장학리' '감정리' '월곡리' '품안리' '품걸리' '신이리' '평촌리' '상걸리']
행정동  : 동산면
법정동 : ['동산면' '조양리' '봉명리' '원창리' '군자리']
행정동  : 신동면
법정동 : ['신동면' '의암리' '팔미리' '혈동리' '증리' '정족리']
행정동  : 남면
법정동 : ['남면' '관천리' '박암리' '가정리' '발산리' '후동리' '추곡리' '한덕리']
행정동  : 서면
법정동 : ['서면' '현암리' '금산리' '신매리' '서상리' '오월리' '월송리' '방동리' '덕두원리' '당림리' '안보리']
행정동  : 사북면
법정동 : ['사북면' '신포리' '지촌리' '오탄리' '가일리' '원평리' '지암리' '고탄리' '고성리' '송암리' '인람리']
행정동  : 북산면
법정동 : ['북산면' '내평리' '청평리' '부귀리' '추곡리' '오항리' '물로리' '조교리' '대동리' '대곡리' '추전리']
행정동  : 동내면
법정동 : ['동내면' '거두리' '신촌리' '고은리' '사암리' '학곡리']
행정동  : 남산면
법정동 : ['남산면' '광판리' '행촌리' '수동리' '창촌리' '방곡리' '강촌리' '서천리' '백양리' '방하리' '산수리']
행정동  : 교동
법정동 : ['교동']
행정동  : 조운동
법정동 : ['조양동' '운교동']
행정동  : 약사명동
법정동 : ['중앙로2가' '중앙로3가' '죽림동' '약사동']
행정동  : 근화동
법정동 : ['소양로1가' '근화동' '중도동']
행정동  : 소양동
법정동 : ['봉의동' '요선동' '낙원동' '중앙로1가' '옥천동' '소양로2가' '소양로3가' '소양로4가']
행정동  : 후평1동
법정동 : ['후평동']
행정동  : 후평2동
법정동 : ['후평동']
행정동  : 후평3동
법정동 : ['후평동']
행정동  : 효자1동
법정동 : ['효자동']
행정동  : 효자2동
법정동 : ['효자동']
행정동  : 효자3동
법정동 : ['효자동']
행정동  : 석사동
법정동 : ['효자동' '석사동']
행정동  : 퇴계동
법정동 : ['퇴계동']
행정동  : 강남동
법정동 : ['온의동' '삼천동' '칠전동' '송암동']
행정동  : 신사우동
법정동 : ['우두동' '사농동' '신동']

## 기타 코드
shp 파일 처리  
읍/면/동 파일과 리 파일의 법정동 코드가 서로 다름  
이를 처리

In [11]:
df['법정동'].unique()

array(['춘천시', '신북읍', '율문리', '천전리', '유포리', '산천리', '발산리', '지내리', '용산리',
       '동면', '만천리', '장학리', '감정리', '월곡리', '품안리', '품걸리', '신이리', '평촌리',
       '상걸리', '동산면', '조양리', '봉명리', '원창리', '군자리', '신동면', '의암리', '팔미리',
       '혈동리', '증리', '정족리', '남면', '관천리', '박암리', '가정리', '후동리', '추곡리', '한덕리',
       '서면', '현암리', '금산리', '신매리', '서상리', '오월리', '월송리', '방동리', '덕두원리',
       '당림리', '안보리', '사북면', '신포리', '지촌리', '오탄리', '가일리', '원평리', '지암리',
       '고탄리', '고성리', '송암리', '인람리', '북산면', '내평리', '청평리', '부귀리', '오항리',
       '물로리', '조교리', '대동리', '대곡리', '추전리', '동내면', '거두리', '신촌리', '고은리',
       '사암리', '학곡리', '남산면', '광판리', '행촌리', '수동리', '창촌리', '방곡리', '강촌리',
       '서천리', '백양리', '방하리', '산수리', '교동', '조양동', '운교동', '중앙로2가', '중앙로3가',
       '죽림동', '약사동', '소양로1가', '근화동', '중도동', '봉의동', '요선동', '낙원동', '중앙로1가',
       '옥천동', '소양로2가', '소양로3가', '소양로4가', '후평동', '효자동', '석사동', '퇴계동',
       '온의동', '삼천동', '칠전동', '송암동', '우두동', '사농동', '신동'], dtype=object)

In [12]:
# shp 파일에서 행정구역 코드만 뽑아내기
df['행정구역분류\n(7자리)'] = df['행정구역분류\n(7자리)'].astype(str)
df['행정구역분류\n(7자리)'] = df['행정구역분류\n(7자리)'].apply(lambda x: x.split('.')[0])
df['행정구역분류\n(7자리)'].unique()

<ipython-input-12-5ff5ed1dfa8e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['행정구역분류\n(7자리)'] = df['행정구역분류\n(7자리)'].astype(str)
<ipython-input-12-5ff5ed1dfa8e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['행정구역분류\n(7자리)'] = df['행정구역분류\n(7자리)'].apply(lambda x: x.split('.')[0])

array(['32010', '3201011', '3201031', '3201032', '3201033', '3201035',
       '3201037', '3201038', '3201039', '3201034', '3201036', '3201052',
       '3201053', '3201054', '3201057', '3201058', '3201060', '3201061',
       '3201062', '3201063', '3201064', '3201065', '3201066', '3201067',
       '3201068', '3201071'], dtype=object)

In [13]:
df['법정동코드'] = df['법정동코드'].astype(str)
df['법정동코드_del'] = df['법정동코드'].apply(lambda x : x[:-2])

<ipython-input-13-9f8b07492973>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['법정동코드'] = df['법정동코드'].astype(str)
<ipython-input-13-9f8b07492973>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['법정동코드_del'] = df['법정동코드'].apply(lambda x : x[:-2])

In [14]:
df[['법정동코드' , '법정동코드_del']].to_csv('ch_STDG_CD.csv' , index=False)