In [1]:
%config Completer.use_jedi = False

In [2]:
import pandas as pd

In [3]:
count = pd.read_csv('2010_2022_count.csv')
count = count[['REG_DTIME' , 'h_dong' , 'count']]
weather = pd.read_csv('2010_2020_weather.csv')
hoilday = pd.read_csv('holiday_2010_2022.csv')
pops = pd.read_csv('./popl/popl.csv')

In [4]:
weather

,Unnamed: 0,REG_DTIME,windspd,humid,temp,precip_form,precip,h_dong
0,0,2010-01-01 00:00:00,0.9,60.562500,-6.137500,0.0,1.5,강남동
1,1,2010-01-01 01:00:00,0.9,60.562500,-6.137500,0.0,1.5,강남동
2,2,2010-01-01 02:00:00,0.9,60.562500,-6.137500,0.0,1.5,강남동
3,3,2010-01-01 03:00:00,0.9,60.562500,-6.137500,0.0,1.5,강남동
4,4,2010-01-01 04:00:00,0.3,61.866667,-6.180000,0.0,1.5,강남동
...,...,...,...,...,...,...,...,...
2410795,8779,2020-12-31 19:00:00,0.9,41.363636,-6.454545,0.0,0.0,후평3동
2410796,8780,2020-12-31 20:00:00,0.9,41.363636,-6.454545,0.0,0.0,후평3동
2410797,8781,2020-12-31 21:00:00,0.9,41.363636,-6.454545,0.0,0.0,후평3동
2410798,8782,2020-12-31 22:00:00,0.9,40.238095,-6.285714,0.0,0.0,후평3동
2410799,8783,2020-12-31 23:00:00,0.9,40.238095,-6.285714,0.0,0.0,후평3동

In [5]:
#weather.rename(columns ={weather.columns[0] : 'REG_DTIME'} , inplace=True)
hoilday.rename(columns ={'date' : 'REG_DTIME'} , inplace=True)
count['REG_DTIME'] = count['REG_DTIME'].astype(str)
weather['REG_DTIME'] = weather['REG_DTIME'].astype(str)
hoilday['REG_DTIME'] = hoilday['REG_DTIME'].astype(str)

In [6]:
m_df = pd.merge(count, weather , how='inner' , on = ['REG_DTIME','h_dong'])
m_df = pd.merge(m_df, pops , how='inner' , on = ['REG_DTIME','h_dong'])
m_df = pd.merge(m_df, hoilday , how='inner' , on = ['REG_DTIME', 'h_dong'])
m_df = m_df.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)
m_df.to_csv('2010_2022.csv')

In [9]:
m_df[m_df['REG_DTIME'] > '2016-01-01 00:00:00'].to_csv('2016_2022.csv')

In [ ]:
weather = pd.read_csv('2010_2020_weather.csv')
weather.rename(columns ={weather.columns[0] : 'REG_DTIME'} , inplace=True)
weather['year'] = pd.to_datetime(weather['REG_DTIME']).dt.year
weather = weather[weather['year'] == 2019]
weather['month'] = pd.to_datetime(weather['REG_DTIME']).dt.month
weather['day'] = pd.to_datetime(weather['REG_DTIME']).dt.day

In [ ]:
weather.isnull().sum()

In [7]:
weather['REG_DTIME']

        REG_DTIME            REG_DTIME
0               0  2010-01-01 00:00:00
1               1  2010-01-01 01:00:00
2               2  2010-01-01 02:00:00
3               3  2010-01-01 03:00:00
4               4  2010-01-01 04:00:00
...           ...                  ...
2410795      8779  2020-12-31 19:00:00
2410796      8780  2020-12-31 20:00:00
2410797      8781  2020-12-31 21:00:00
2410798      8782  2020-12-31 22:00:00
2410799      8783  2020-12-31 23:00:00

[2410800 rows x 2 columns]